<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Ballware.Meta.Data\Ballware.Meta.Data.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Ballware.Shared.Mcp" Version="1.2.0-alpha.14" />
      <PackageReference Include="Ballware.Shared.Mcp.Authorization" Version="1.2.0-alpha.14" />
      <PackageReference Include="Mapster" Version="7.4.0" />
      <PackageReference Include="NJsonSchema" Version="11.5.2" />
    </ItemGroup>

</Project>
