name: Publish NuGet Packages
on:
  push:
    branches:
      - main
      - develop

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version:
            8.0
      - name: Install GitVersion
        run: dotnet tool install --global GitVersion.Tool
      - name: Determine version
        id: version
        run: |
          VERSION=$(dotnet-gitversion /showvariable SemVer)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      - name: Output determined version
        run: echo
      - name: Pack NuGet packages
        run: |
          dotnet restore ballware-meta-service.sln
          dotnet pack ballware-meta-service.sln -p:Version=${{ env.VERSION }} --configuration Release --output ./nupkgs
      - name: Publish NuGet packages to GitHub Packages
        run: |
          dotnet nuget push ./nupkgs/*.nupkg --source https://nuget.pkg.github.com/ballware/index.json --api-key ${{ secrets.GITHUB_TOKEN }}